### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by morty** [datagovuk/contracts-archive#1]
- [x] Put search at top of every page
- [ ] Warning about archived data on every page
- [ ] Finish data feeds page

**Comment by davidread** [comment]
Data feeds - No need for the RSS feeds. But add info on the front page about what they are. On data page, change text to past tense.
